version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-tecde
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TecDeCuliacann
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/00_schema.sql:ro
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_seed.sql:ro

volumes:
  postgres_data:
